---
- hosts: server
  remote_user: root
  become: true
  tasks:
  # - name: "Installing epel-release packages"
  #   yum:
  #     name: epel-release
  #     state: present

  - name: "Installing system packages"
    yum:
      name: ['net-tools', 'telnet', 'vim', 'iptables-services']
      state: present

  - name: Installing Docker Prerequisite packages
    yum:
      name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2', 'xfsprogs']
      state: present

  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: "Installing Docker latest"
    yum:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python-docker']
      state: present

  - name: " Starting and Enabling Docker service"
    service:
      name: docker
      state: started
      enabled: yes

  - name: Stop firewalld
    service: name=firewalld state=stopped

  - name: Disable firewalld
    service: name=firewalld enabled=no

  - name: Mask firewalld
    service: name=firewalld masked=yes

  - name: Start iptables service
    systemd:
      state: started
      name: iptables
      enabled: yes
  - name: Login DockerHub
    shell: docker login -u "{{DOCKER_USERNAME}}" -p "{{DOCKER_PASSWORD}}"
  - name: Copy file
    copy:
      src: docker-compose.yaml
      dest: /home/centos/
  - name: Restart docker-compose
    shell: |
        docker-compose stop
        docker-compose rm -f
        docker-compose pull
        docker-compose up -d
...
  